# Generated by Django 4.2.1 on 2025-01-10 10:27

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company_Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('com_name', models.CharField(blank=True, max_length=200, null=True)),
                ('admin_id', models.CharField(default=uuid.uuid4, max_length=200, unique=True)),
                ('gst_no', models.CharField(max_length=200, unique=True)),
                ('mobile', models.CharField(blank=True, max_length=200, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(blank=True, max_length=25, null=True)),
                ('pincode', models.CharField(blank=True, max_length=6, null=True)),
                ('state', models.CharField(blank=True, max_length=30, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=30, null=True)),
                ('account_name', models.CharField(blank=True, max_length=30, null=True)),
                ('account_no', models.CharField(blank=True, max_length=30, null=True)),
                ('ifc', models.CharField(blank=True, max_length=30, null=True)),
                ('bank_address', models.CharField(blank=True, max_length=30, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Company_Name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_company_name', models.CharField(blank=True, max_length=200, null=True)),
                ('company_id', models.CharField(default=uuid.uuid4, max_length=200, unique=True)),
                ('company_gst_no', models.CharField(max_length=200, unique=True)),
                ('company_mobile', models.CharField(blank=True, max_length=200, null=True)),
                ('company_address', models.CharField(blank=True, max_length=200, null=True)),
                ('company_city', models.CharField(blank=True, max_length=25, null=True)),
                ('company_pincode', models.CharField(blank=True, max_length=6, null=True)),
                ('company_state', models.CharField(blank=True, max_length=30, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('company_admin_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.company_admin')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(blank=True, max_length=200, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_leader_name', models.CharField(blank=True, max_length=200, null=True)),
                ('associate_name', models.CharField(blank=True, max_length=200, null=True)),
                ('plot', models.CharField(blank=True, max_length=200, null=True)),
                ('plot_size', models.CharField(blank=True, max_length=200, null=True)),
                ('client_name', models.CharField(blank=True, max_length=200, null=True)),
                ('mobile', models.CharField(max_length=13)),
                ('total_price', models.IntegerField(blank=True, null=True)),
                ('discount', models.CharField(blank=True, max_length=15, null=True)),
                ('agreement_values', models.CharField(blank=True, max_length=15, null=True)),
                ('deal_values', models.CharField(blank=True, max_length=15, null=True)),
                ('cash_amount', models.CharField(blank=True, max_length=15, null=True)),
                ('cheque_amount', models.CharField(blank=True, max_length=15, null=True)),
                ('cheque_no', models.CharField(blank=True, max_length=6, null=True)),
                ('sum_amount', models.CharField(blank=True, max_length=15, null=True)),
                ('remaining_amount', models.CharField(blank=True, max_length=15, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.project')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(blank=True, max_length=10, null=True)),
                ('cheque_number', models.CharField(blank=True, max_length=15, null=True)),
                ('cheque_amount', models.CharField(blank=True, max_length=15, null=True)),
                ('case_amount', models.CharField(blank=True, max_length=20, null=True)),
                ('total_amount', models.CharField(blank=True, max_length=20, null=True)),
                ('remaining_amount', models.CharField(blank=True, max_length=20, null=True)),
                ('received_amount', models.CharField(blank=True, max_length=20, null=True)),
                ('payment_description', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('records', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.record')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice', models.CharField(choices=[('sales', 'Sales'), ('purchase', 'Purchases')], default='Sales', max_length=255)),
                ('invoice_no', models.CharField(blank=True, max_length=200, null=True)),
                ('product_service', models.CharField(blank=True, max_length=200, null=True)),
                ('hsn_code', models.CharField(blank=True, max_length=200, null=True)),
                ('qty', models.CharField(blank=True, max_length=200, null=True)),
                ('rate', models.CharField(blank=True, max_length=200, null=True)),
                ('amount', models.CharField(blank=True, max_length=200, null=True)),
                ('gst_rate', models.IntegerField(choices=[(12, '12%'), (18, '18%'), (28, '28%')], default=18)),
                ('total_amount', models.IntegerField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('company_na', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.company_name')),
            ],
        ),
    ]
